#ifndef MYTESTRUNNER_GLOBAL_H
#define MYTESTRUNNER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYTESTRUNNER_LIBRARY)
#  define MYTESTRUNNERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MYTESTRUNNERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MYTESTRUNNER_GLOBAL_H
